production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: main
  queue:
    <<: *default
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    database: queue
  cable:
    <<: *default
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    database: cable

