class RemoveBooleanAmenityColumnsFromListingsAndModelHouses < ActiveRecord::Migration[8.0]
  def change
    # --- Remove from listings ---
    remove_column :listings, :guardhouse, :boolean
    remove_column :listings, :perimeterfence, :boolean
    remove_column :listings, :cctv, :boolean
    remove_column :listings, :clubhouse, :boolean
    remove_column :listings, :pool, :boolean
    remove_column :listings, :coveredcourt, :boolean
    remove_column :listings, :parks, :boolean
    remove_column :listings, :playground, :boolean
    remove_column :listings, :joggingpaths, :boolean
    remove_column :listings, :conveniencestore, :boolean
    remove_column :listings, :watersystem, :boolean
    remove_column :listings, :drainagesystem, :boolean
    remove_column :listings, :undergroundlines, :boolean
    remove_column :listings, :wastemgmt, :boolean
    remove_column :listings, :garden, :boolean
    remove_column :listings, :carport, :boolean
    remove_column :listings, :dirtykitchen, :boolean
    remove_column :listings, :gate, :boolean
    remove_column :listings, :watertank, :boolean
    remove_column :listings, :homecctv, :boolean
    remove_column :listings, :homepool, :boolean
    remove_column :listings, :lanai, :boolean
    remove_column :listings, :landscaping, :boolean
    remove_column :listings, :aircon, :boolean
    remove_column :listings, :wardrobes, :boolean
    remove_column :listings, :modkitchen, :boolean
    remove_column :listings, :crfixtures, :boolean
    remove_column :listings, :lightfixtures, :boolean
    remove_column :listings, :firesystem, :boolean
    remove_column :listings, :intercom, :boolean
    remove_column :listings, :internetprov, :boolean
    remove_column :listings, :cableprov, :boolean
    remove_column :listings, :meterperunit, :boolean
    remove_column :listings, :washingmachineprov, :boolean
    remove_column :listings, :waterheaterprov, :boolean
    remove_column :listings, :smarthomeready, :boolean
    remove_column :listings, :balcony, :boolean
    remove_column :listings, :cityview, :boolean
    remove_column :listings, :mountainview, :boolean
    remove_column :listings, :petfriendly, :boolean
    remove_column :listings, :facingeast, :boolean

    # --- Remove from model_houses ---
    remove_column :model_houses, :guardhouse, :boolean
    remove_column :model_houses, :perimeterfence, :boolean
    remove_column :model_houses, :cctv, :boolean
    remove_column :model_houses, :clubhouse, :boolean
    remove_column :model_houses, :pool, :boolean
    remove_column :model_houses, :coveredcourt, :boolean
    remove_column :model_houses, :parks, :boolean
    remove_column :model_houses, :playground, :boolean
    remove_column :model_houses, :joggingpaths, :boolean
    remove_column :model_houses, :conveniencestore, :boolean
    remove_column :model_houses, :watersystem, :boolean
    remove_column :model_houses, :drainagesystem, :boolean
    remove_column :model_houses, :undergroundlines, :boolean
    remove_column :model_houses, :wastemgmt, :boolean
    remove_column :model_houses, :garden, :boolean
    remove_column :model_houses, :carport, :boolean
    remove_column :model_houses, :dirtykitchen, :boolean
    remove_column :model_houses, :gate, :boolean
    remove_column :model_houses, :watertank, :boolean
    remove_column :model_houses, :homecctv, :boolean
    remove_column :model_houses, :homepool, :boolean
    remove_column :model_houses, :lanai, :boolean
    remove_column :model_houses, :landscaping, :boolean
    remove_column :model_houses, :aircon, :boolean
    remove_column :model_houses, :wardrobes, :boolean
    remove_column :model_houses, :modkitchen, :boolean
    remove_column :model_houses, :crfixtures, :boolean
    remove_column :model_houses, :lightfixtures, :boolean
    remove_column :model_houses, :firesystem, :boolean
    remove_column :model_houses, :intercom, :boolean
    remove_column :model_houses, :internetprov, :boolean
    remove_column :model_houses, :cableprov, :boolean
    remove_column :model_houses, :meterperunit, :boolean
    remove_column :model_houses, :washingmachineprov, :boolean
    remove_column :model_houses, :waterheaterprov, :boolean
    remove_column :model_houses, :smarthomeready, :boolean
    remove_column :model_houses, :balcony, :boolean
    remove_column :model_houses, :cityview, :boolean
    remove_column :model_houses, :mountainview, :boolean
    remove_column :model_houses, :petfriendly, :boolean
    remove_column :model_houses, :facingeast, :boolean
  end
end
